import { PhysicalDimensions, DIMENSIONS } from './dimensions';
import { PickupData } from './evaluator';

export const GAME_PICKUPS: PickupData[] = [
  // ==========================================
  // 1. MECHANICS OPERATORS
  // ==========================================
  {
    id: 'op_v',
    symbol: '×v',
    label: 'Multiply Velocity (×v)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.VELOCITY,
    color: '#f59e0b',
    rarity: 'common',
    domain: 'Mechanics',
  },
  {
    id: 'op_inv_m',
    symbol: '1/m',
    label: 'Divide by Mass (1/m)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.INVERSE_MASS,
    color: '#34d399',
    rarity: 'common',
    domain: 'Mechanics',
  },
  {
    id: 'op_ddt',
    symbol: 'd/dt',
    label: 'Time Derivative (d/dt)',
    category: 'CALCULUS',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    color: '#ec4899',
    rarity: 'common',
    domain: 'Mechanics',
  },
  {
    id: 'op_integral_dt',
    symbol: '∫dt',
    label: 'Time Integral (∫dt)',
    category: 'CALCULUS',
    operandDimension: DIMENSIONS.TIME,
    color: '#10b981',
    rarity: 'uncommon',
    domain: 'Mechanics',
  },
  {
    id: 'op_times_m',
    symbol: '×m',
    label: 'Multiply Mass (×m)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.MASS,
    color: '#38bdf8',
    rarity: 'common',
    domain: 'Mechanics',
  },
  {
    id: 'op_times_t',
    symbol: '×t',
    label: 'Multiply Time (×t)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.TIME,
    color: '#fb923c',
    rarity: 'common',
    domain: 'Mechanics',
  },
  {
    id: 'op_div_t',
    symbol: '/t',
    label: 'Divide by Time (/t)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    color: '#eab308',
    rarity: 'common',
    domain: 'Mechanics',
  },
  {
    id: 'op_times_s',
    symbol: '×s',
    label: 'Multiply Distance (×s)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.LENGTH,
    color: '#a855f7',
    rarity: 'common',
    domain: 'Mechanics',
  },

  // ==========================================
  // 2. ENERGY INGREDIENTS & OPERATORS
  // ==========================================
  {
    id: 'op_half_v2',
    symbol: '×(½v²)',
    label: 'Kinetic Factor (×½v²)',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(0, 2, -2, 0),
    color: '#06b6d4',
    rarity: 'uncommon',
    domain: 'Energy',
  },
  {
    id: 'op_v_half',
    symbol: '×(v/2)',
    label: 'Half-Velocity (×v/2)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.VELOCITY,
    color: '#06b6d4',
    rarity: 'uncommon',
    domain: 'Energy',
  },
  {
    id: 'op_gh',
    symbol: '×(gh)',
    label: 'Gravitational Factor (×gh)',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(0, 2, -2, 0),
    color: '#8b5cf6',
    rarity: 'uncommon',
    domain: 'Energy',
  },
  {
    id: 'op_g',
    symbol: '×g',
    label: 'Gravity Field (×g)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.ACCELERATION,
    color: '#8b5cf6',
    rarity: 'uncommon',
    domain: 'Energy',
  },
  {
    id: 'op_h',
    symbol: '×h',
    label: 'Height (×h)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.LENGTH,
    color: '#a78bfa',
    rarity: 'uncommon',
    domain: 'Energy',
  },

  // ==========================================
  // 3. ROTATIONAL OPERATORS
  // ==========================================
  {
    id: 'op_r2',
    symbol: '×r²',
    label: 'Radius Squared (×r²)',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(0, 2, 0, 0),
    color: '#6366f1',
    rarity: 'uncommon',
    domain: 'Rotational',
  },
  {
    id: 'op_r',
    symbol: '×r',
    label: 'Lever Arm (×r)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.LENGTH,
    color: '#d946ef',
    rarity: 'uncommon',
    domain: 'Rotational',
  },
  {
    id: 'op_div_r',
    symbol: '/r',
    label: 'Divide by Radius (/r)',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(0, -1, 0, 0),
    color: '#14b8a6',
    rarity: 'uncommon',
    domain: 'Rotational',
  },
  {
    id: 'op_alpha',
    symbol: '×α',
    label: 'Angular Accel (×α)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.ANGULAR_ACCELERATION,
    color: '#f43f5e',
    rarity: 'rare',
    domain: 'Rotational',
  },
  {
    id: 'op_omega',
    symbol: '×ω',
    label: 'Angular Velocity (×ω)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.ANGULAR_VELOCITY,
    color: '#84cc16',
    rarity: 'rare',
    domain: 'Rotational',
  },

  // ==========================================
  // 4. ELECTRODYNAMICS & MAGNETISM OPERATORS
  // ==========================================
  {
    id: 'op_I',
    symbol: '×I',
    label: 'Multiply Current (×I)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.CURRENT,
    color: '#facc15',
    rarity: 'uncommon',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_div_I',
    symbol: '/I',
    label: 'Divide by Current (/I)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.INVERSE_CURRENT,
    color: '#fb7185',
    rarity: 'uncommon',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_V',
    symbol: '×V',
    label: 'Multiply Voltage (×V)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.VOLTAGE,
    color: '#60a5fa',
    rarity: 'uncommon',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_div_V',
    symbol: '/V',
    label: 'Divide by Voltage (/V)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.INVERSE_VOLTAGE,
    color: '#38bdf8',
    rarity: 'uncommon',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_R',
    symbol: '×R',
    label: 'Multiply Resistance (×R)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.RESISTANCE,
    color: '#fb7185',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_E',
    symbol: '×E',
    label: 'Electric Field (×E)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.ELECTRIC_FIELD,
    color: '#c084fc',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_div_q',
    symbol: '/q',
    label: 'Divide by Charge (/q)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.INVERSE_CHARGE,
    color: '#c084fc',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_vB',
    symbol: '×(vB)',
    label: 'Lorentz Factor (×vB)',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(1, 1, -3, -1),
    color: '#0ea5e9',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_LB',
    symbol: '×(LB)',
    label: 'Laplace Factor (×LB)',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(1, 1, -2, -1),
    color: '#0ea5e9',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },


  // ==========================================
  // 5. EVOLUTION BRIDGE / REVERSE PICKUPS
  // These symbols deliberately connect branches and prevent dead-end states.
  // ==========================================
  {
    id: 'op_dt_energy',
    symbol: 'd/dt',
    label: 'Energy Rate (d/dt)',
    category: 'CALCULUS',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    color: '#22d3ee',
    rarity: 'uncommon',
    domain: 'Energy',
  },
  {
    id: 'op_theta_t',
    symbol: '×t',
    label: 'Time Sweep (×t)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.TIME,
    color: '#818cf8',
    rarity: 'uncommon',
    domain: 'Rotational',
  },
  {
    id: 'op_q',
    symbol: '×q',
    label: 'Charge (×q)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.CHARGE,
    color: '#f472b6',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_div_V_to_q',
    symbol: '/V',
    label: 'Divide by Voltage (/V)',
    category: 'OPERATOR',
    operandDimension: DIMENSIONS.INVERSE_VOLTAGE,
    color: '#38bdf8',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_div_E',
    symbol: '/E',
    label: 'Divide by Electric Field (/E)',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(-1, -1, 3, 1),
    color: '#c084fc',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_qv',
    symbol: '×(qv)',
    label: 'Charge × Velocity (×qv)',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(0, 1, 0, 1),
    color: '#22d3ee',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  {
    id: 'op_div_qv',
    symbol: '/(qv)',
    label: 'Divide by Charge × Velocity (/(qv))',
    category: 'OPERATOR',
    operandDimension: new PhysicalDimensions(0, -1, 0, -1),
    color: '#0284c7',
    rarity: 'rare',
    domain: 'Electromagnetism',
  },
  // ==========================================
  // 5. MAGNITUDE MODIFIERS
  // ==========================================
  // Mass Modifiers
  {
    id: 'plus_m',
    symbol: '+m',
    label: '+Mass (+1 kg)',
    category: 'MODIFIER',
    targetQuantity: 'm',
    deltaValue: 1,
    operandDimension: DIMENSIONS.MASS,
    color: '#38bdf8',
    rarity: 'common',
  },
  {
    id: 'minus_m',
    symbol: '-m',
    label: '-Mass (-1 kg)',
    category: 'MODIFIER',
    targetQuantity: 'm',
    deltaValue: -1,
    operandDimension: DIMENSIONS.MASS,
    color: '#0284c7',
    rarity: 'common',
  },
  // Velocity Modifiers
  {
    id: 'plus_v',
    symbol: '+v',
    label: '+Velocity (+5 m/s)',
    category: 'MODIFIER',
    targetQuantity: 'v',
    deltaValue: 5,
    operandDimension: DIMENSIONS.VELOCITY,
    color: '#34d399',
    rarity: 'common',
  },
  {
    id: 'minus_v',
    symbol: '-v',
    label: '-Velocity (-5 m/s)',
    category: 'MODIFIER',
    targetQuantity: 'v',
    deltaValue: -5,
    operandDimension: DIMENSIONS.VELOCITY,
    color: '#059669',
    rarity: 'common',
  },
  // Momentum Modifiers
  {
    id: 'plus_p',
    symbol: '+p',
    label: '+Momentum (+10 kg·m/s)',
    category: 'MODIFIER',
    targetQuantity: 'p',
    deltaValue: 10,
    operandDimension: DIMENSIONS.MOMENTUM,
    color: '#f59e0b',
    rarity: 'common',
  },
  {
    id: 'minus_p',
    symbol: '-p',
    label: '-Momentum (-10 kg·m/s)',
    category: 'MODIFIER',
    targetQuantity: 'p',
    deltaValue: -10,
    operandDimension: DIMENSIONS.MOMENTUM,
    color: '#d97706',
    rarity: 'common',
  },
  // Force Modifiers
  {
    id: 'plus_F',
    symbol: '+F',
    label: '+Force (+10 N)',
    category: 'MODIFIER',
    targetQuantity: 'F',
    deltaValue: 10,
    operandDimension: DIMENSIONS.FORCE,
    color: '#ef4444',
    rarity: 'uncommon',
  },
  {
    id: 'minus_F',
    symbol: '-F',
    label: '-Force (-10 N)',
    category: 'MODIFIER',
    targetQuantity: 'F',
    deltaValue: -10,
    operandDimension: DIMENSIONS.FORCE,
    color: '#b91c1c',
    rarity: 'uncommon',
  },
  // Work / Energy Modifiers
  {
    id: 'plus_W',
    symbol: '+W',
    label: '+Work (+25 J)',
    category: 'MODIFIER',
    targetQuantity: 'W',
    deltaValue: 25,
    operandDimension: DIMENSIONS.WORK_ENERGY,
    color: '#a855f7',
    rarity: 'uncommon',
  },
  // Power Modifiers
  {
    id: 'plus_P',
    symbol: '+P',
    label: '+Power (+20 W)',
    category: 'MODIFIER',
    targetQuantity: 'P',
    deltaValue: 20,
    operandDimension: DIMENSIONS.POWER,
    color: '#eab308',
    rarity: 'uncommon',
  },
];
