import { PhysicalDimensions, DIMENSIONS } from './dimensions';
import { QuantityId } from './quantities';

export interface TransformationRule {
  id: string;
  name: string;
  domain: 'Mechanics' | 'Energy' | 'Rotational' | 'Electromagnetism';
  inputQuantity: QuantityId;
  operatorSymbol: string;
  operandDimension: PhysicalDimensions;
  outputQuantity: QuantityId;
  formula: string;
  educationalNote: string;
  isMultiStep?: boolean;
  requiredIngredients?: string[]; // E.g. ['g', 'h'] or ['v', 'B']
  calculateValue: (currentVal: number) => number;
}

export const PHYSICS_TRANSFORMATIONS: TransformationRule[] = [
  // ==========================================
  // 1. MECHANICS CORE
  // ==========================================
  {
    id: 'm_times_v',
    name: 'Mass → Momentum',
    domain: 'Mechanics',
    inputQuantity: 'm',
    operatorSymbol: '×v',
    operandDimension: DIMENSIONS.VELOCITY,
    outputQuantity: 'p',
    formula: 'p = m × v',
    educationalNote: 'Linear momentum is mass multiplied by velocity: [M] × [L T⁻¹] = [M L T⁻¹]. Momentum represents the overall quantity of motion.',
    calculateValue: (m) => Number((m * 15).toFixed(1)),
  },
  {
    id: 'p_times_inv_m',
    name: 'Momentum → Velocity',
    domain: 'Mechanics',
    inputQuantity: 'p',
    operatorSymbol: '1/m',
    operandDimension: DIMENSIONS.INVERSE_MASS,
    outputQuantity: 'v',
    formula: 'v = p / m',
    educationalNote: 'Dividing momentum by mass isolates velocity: [M L T⁻¹] × [M⁻¹] = [L T⁻¹]. Velocity is the rate of change of displacement.',
    calculateValue: (p) => Math.max(10, Number((p / 5).toFixed(1))),
  },
  {
    id: 'v_times_ddt',
    name: 'Velocity → Acceleration',
    domain: 'Mechanics',
    inputQuantity: 'v',
    operatorSymbol: 'd/dt',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'a',
    formula: 'a = dv/dt',
    educationalNote: 'Taking the time derivative of velocity yields acceleration: [L T⁻¹] × [T⁻¹] = [L T⁻²].',
    calculateValue: (v) => Number((v * 0.8).toFixed(1)),
  },
  {
    id: 'a_times_integral_dt',
    name: 'Acceleration → Velocity',
    domain: 'Mechanics',
    inputQuantity: 'a',
    operatorSymbol: '∫dt',
    operandDimension: DIMENSIONS.TIME,
    outputQuantity: 'v',
    formula: 'v = ∫a dt',
    educationalNote: 'Integrating acceleration over time yields velocity: [L T⁻²] × [T] = [L T⁻¹]. (Simplified game transformation).',
    calculateValue: (a) => Number((a * 2.5).toFixed(1)),
  },
  {
    id: 'a_times_m',
    name: 'Acceleration → Force',
    domain: 'Mechanics',
    inputQuantity: 'a',
    operatorSymbol: '×m',
    operandDimension: DIMENSIONS.MASS,
    outputQuantity: 'F',
    formula: 'F = m × a',
    educationalNote: 'Newton’s Second Law: Force equals mass times acceleration: [L T⁻²] × [M] = [M L T⁻²].',
    calculateValue: (a) => Number((a * 5).toFixed(1)),
  },
  {
    id: 'p_times_ddt',
    name: 'Momentum → Force',
    domain: 'Mechanics',
    inputQuantity: 'p',
    operatorSymbol: 'd/dt',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'F',
    formula: 'F = dp/dt',
    educationalNote: 'Newton’s Second Law in momentum form: Force is the time-rate of change of linear momentum: [M L T⁻¹] × [T⁻¹] = [M L T⁻²].',
    calculateValue: (p) => Number((p * 0.7).toFixed(1)),
  },
  {
    id: 'F_times_t',
    name: 'Force → Impulse',
    domain: 'Mechanics',
    inputQuantity: 'F',
    operatorSymbol: '×t',
    operandDimension: DIMENSIONS.TIME,
    outputQuantity: 'J',
    formula: 'J = F × t',
    educationalNote: 'Impulse is force exerted over a time interval: [M L T⁻²] × [T] = [M L T⁻¹]. Impulse equals the change in momentum (Δp).',
    calculateValue: (F) => Number((F * 1.5).toFixed(1)),
  },
  {
    id: 'J_div_t',
    name: 'Impulse → Force',
    domain: 'Mechanics',
    inputQuantity: 'J',
    operatorSymbol: '/t',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'F',
    formula: 'F = J / t',
    educationalNote: 'Dividing impulse by duration yields the average applied force: [M L T⁻¹] × [T⁻¹] = [M L T⁻²].',
    calculateValue: (J) => Number((J / 1.5).toFixed(1)),
  },
  {
    id: 'F_times_s',
    name: 'Force → Work',
    domain: 'Mechanics',
    inputQuantity: 'F',
    operatorSymbol: '×s',
    operandDimension: DIMENSIONS.LENGTH,
    outputQuantity: 'W',
    formula: 'W = F × s',
    educationalNote: 'Work is force applied across a displacement: [M L T⁻²] × [L] = [M L² T⁻²]. Work transfers energy to a system.',
    calculateValue: (F) => Number((F * 4).toFixed(1)),
  },
  {
    id: 'W_div_t',
    name: 'Work → Power',
    domain: 'Mechanics',
    inputQuantity: 'W',
    operatorSymbol: '/t',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'P',
    formula: 'P = W / t',
    educationalNote: 'Power is the rate at which work is performed: [M L² T⁻²] × [T⁻¹] = [M L² T⁻³]. Measured in Watts (J/s).',
    calculateValue: (W) => Number((W * 0.5).toFixed(1)),
  },
  {
    id: 'P_times_t',
    name: 'Power → Work',
    domain: 'Mechanics',
    inputQuantity: 'P',
    operatorSymbol: '×t',
    operandDimension: DIMENSIONS.TIME,
    outputQuantity: 'W',
    formula: 'W = P × t',
    educationalNote: 'Integrating power over a time interval yields total work done: [M L² T⁻³] × [T] = [M L² T⁻²].',
    calculateValue: (P) => Number((P * 2).toFixed(1)),
  },

  // ==========================================
  // 2. ENERGY BRANCH (KE, PE)
  // ==========================================
  {
    id: 'm_to_KE',
    name: 'Mass → Kinetic Energy',
    domain: 'Energy',
    inputQuantity: 'm',
    operatorSymbol: '×(½v²)',
    operandDimension: new PhysicalDimensions(0, 2, -2, 0), // [L² T⁻²]
    outputQuantity: 'KE',
    formula: 'KE = ½ × m × v²',
    educationalNote: 'Kinetic energy scales with mass and the square of velocity: [M] × [L² T⁻²] = [M L² T⁻²]. ½ is a dimensionless scalar.',
    calculateValue: (m) => Number((0.5 * m * 15 * 15).toFixed(1)),
  },
  {
    id: 'p_to_KE',
    name: 'Momentum → Kinetic Energy',
    domain: 'Energy',
    inputQuantity: 'p',
    operatorSymbol: '×(v/2)',
    operandDimension: DIMENSIONS.VELOCITY,
    outputQuantity: 'KE',
    formula: 'KE = p × v / 2 = p² / (2m)',
    educationalNote: 'Kinetic energy expressed via momentum: [M L T⁻¹] × [L T⁻¹] = [M L² T⁻²].',
    calculateValue: (p) => Number(((p * p) / (2 * 5)).toFixed(1)),
  },
  {
    id: 'm_to_PE',
    name: 'Mass → Potential Energy',
    domain: 'Energy',
    inputQuantity: 'm',
    operatorSymbol: '×(gh)',
    operandDimension: new PhysicalDimensions(0, 2, -2, 0), // [L T⁻²] × [L] = [L² T⁻²]
    outputQuantity: 'PE',
    formula: 'PE = m × g × h',
    educationalNote: 'Gravitational potential energy is mass in gravitational field g at height h: [M] × [L T⁻²] × [L] = [M L² T⁻²].',
    calculateValue: (m) => Number((m * 9.8 * 10).toFixed(1)),
  },

  // ==========================================
  // 3. ROTATIONAL MECHANICS BRANCH
  // ==========================================
  {
    id: 'theta_times_ddt',
    name: 'Angular Displacement → Angular Velocity',
    domain: 'Rotational',
    inputQuantity: 'theta',
    operatorSymbol: 'd/dt',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'omega',
    formula: 'ω = dθ/dt',
    educationalNote: 'Time derivative of angular displacement produces angular velocity: [1] × [T⁻¹] = [T⁻¹]. Expressed in rad/s.',
    calculateValue: () => 12.0,
  },
  {
    id: 'omega_times_ddt',
    name: 'Angular Velocity → Angular Acceleration',
    domain: 'Rotational',
    inputQuantity: 'omega',
    operatorSymbol: 'd/dt',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'alpha',
    formula: 'α = dω/dt',
    educationalNote: 'Time rate of change of angular velocity is angular acceleration: [T⁻¹] × [T⁻¹] = [T⁻²].',
    calculateValue: (omega) => Number((omega * 1.2).toFixed(1)),
  },
  {
    id: 'I_times_alpha',
    name: 'Moment of Inertia → Torque',
    domain: 'Rotational',
    inputQuantity: 'I_rot',
    operatorSymbol: '×α',
    operandDimension: DIMENSIONS.ANGULAR_ACCELERATION,
    outputQuantity: 'tau',
    formula: 'τ = I × α',
    educationalNote: 'Rotational equivalent of F = ma: Torque equals moment of inertia times angular acceleration: [M L²] × [T⁻²] = [M L² T⁻²].',
    calculateValue: (I) => Number((I * 8).toFixed(1)),
  },
  {
    id: 'I_times_omega',
    name: 'Moment of Inertia → Angular Momentum',
    domain: 'Rotational',
    inputQuantity: 'I_rot',
    operatorSymbol: '×ω',
    operandDimension: DIMENSIONS.ANGULAR_VELOCITY,
    outputQuantity: 'L_rot',
    formula: 'L = I × ω',
    educationalNote: 'Angular momentum is moment of inertia multiplied by angular velocity: [M L²] × [T⁻¹] = [M L² T⁻¹]. Conserved in isolated rotations.',
    calculateValue: (I) => Number((I * 12).toFixed(1)),
  },
  {
    id: 'L_times_ddt',
    name: 'Angular Momentum → Torque',
    domain: 'Rotational',
    inputQuantity: 'L_rot',
    operatorSymbol: 'd/dt',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'tau',
    formula: 'τ = dL/dt',
    educationalNote: 'Torque is the time rate of change of angular momentum: [M L² T⁻¹] × [T⁻¹] = [M L² T⁻²].',
    calculateValue: (L) => Number((L * 0.75).toFixed(1)),
  },
  // Bridge between Linear & Rotational Mechanics
  {
    id: 'm_times_r2',
    name: 'Mass → Moment of Inertia',
    domain: 'Rotational',
    inputQuantity: 'm',
    operatorSymbol: '×r²',
    operandDimension: new PhysicalDimensions(0, 2, 0, 0), // [L²]
    outputQuantity: 'I_rot',
    formula: 'I = m × r²',
    educationalNote: 'Moment of inertia for a point mass at radius r: [M] × [L²] = [M L²].',
    calculateValue: (m) => Number((m * 4).toFixed(1)),
  },
  {
    id: 'F_times_r',
    name: 'Force → Torque',
    domain: 'Rotational',
    inputQuantity: 'F',
    operatorSymbol: '×r',
    operandDimension: DIMENSIONS.LENGTH,
    outputQuantity: 'tau',
    formula: 'τ = r × F',
    educationalNote: 'Torque is lever arm perpendicular distance multiplied by force: [M L T⁻²] × [L] = [M L² T⁻²].',
    calculateValue: (F) => Number((F * 2).toFixed(1)),
  },
  {
    id: 'tau_div_r',
    name: 'Torque → Force',
    domain: 'Mechanics',
    inputQuantity: 'tau',
    operatorSymbol: '/r',
    operandDimension: new PhysicalDimensions(0, -1, 0, 0), // [L⁻¹]
    outputQuantity: 'F',
    formula: 'F = τ / r',
    educationalNote: 'Dividing torque by lever arm radius isolates linear force: [M L² T⁻²] × [L⁻¹] = [M L T⁻²].',
    calculateValue: (tau) => Number((tau / 2).toFixed(1)),
  },
  {
    id: 'v_div_r',
    name: 'Velocity → Angular Velocity',
    domain: 'Rotational',
    inputQuantity: 'v',
    operatorSymbol: '/r',
    operandDimension: new PhysicalDimensions(0, -1, 0, 0), // [L⁻¹]
    outputQuantity: 'omega',
    formula: 'ω = v / r',
    educationalNote: 'Tangential velocity divided by radius gives angular velocity: [L T⁻¹] × [L⁻¹] = [T⁻¹].',
    calculateValue: (v) => Number((v / 2).toFixed(1)),
  },

  // ==========================================
  // 4. ELECTRODYNAMICS & MAGNETISM BRANCH
  // ==========================================
  {
    id: 'q_times_ddt',
    name: 'Charge → Electric Current',
    domain: 'Electromagnetism',
    inputQuantity: 'q',
    operatorSymbol: 'd/dt',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'I_elec',
    formula: 'I = dq/dt',
    educationalNote: 'Electric current is the time rate of flow of electric charge: [T I] × [T⁻¹] = [I]. Measured in Amperes (C/s).',
    calculateValue: (q) => Number((q * 1.5).toFixed(1)),
  },
  {
    id: 'V_times_I',
    name: 'Voltage → Electric Power',
    domain: 'Electromagnetism',
    inputQuantity: 'V',
    operatorSymbol: '×I',
    operandDimension: DIMENSIONS.CURRENT,
    outputQuantity: 'P',
    formula: 'P = V × I',
    educationalNote: 'Joule’s Law: Electric power equals potential difference multiplied by current: [M L² T⁻³ I⁻¹] × [I] = [M L² T⁻³].',
    calculateValue: (V) => Number((V * 3).toFixed(1)),
  },
  {
    id: 'V_div_I',
    name: 'Voltage → Resistance',
    domain: 'Electromagnetism',
    inputQuantity: 'V',
    operatorSymbol: '/I',
    operandDimension: DIMENSIONS.INVERSE_CURRENT,
    outputQuantity: 'R',
    formula: 'R = V / I',
    educationalNote: 'Ohm’s Law: Resistance is ratio of voltage to electric current: [M L² T⁻³ I⁻¹] × [I⁻¹] = [M L² T⁻³ I⁻²]. Measured in Ohms (Ω).',
    calculateValue: (V) => Number((V / 3).toFixed(1)),
  },
  {
    id: 'I_times_R',
    name: 'Current → Voltage',
    domain: 'Electromagnetism',
    inputQuantity: 'I_elec',
    operatorSymbol: '×R',
    operandDimension: DIMENSIONS.RESISTANCE,
    outputQuantity: 'V',
    formula: 'V = I × R',
    educationalNote: 'Ohm’s Law: Voltage drop equals electric current times resistance: [I] × [M L² T⁻³ I⁻²] = [M L² T⁻³ I⁻¹].',
    calculateValue: (I) => Number((I * 10).toFixed(1)),
  },
  {
    id: 'q_times_V',
    name: 'Charge → Energy (Work)',
    domain: 'Electromagnetism',
    inputQuantity: 'q',
    operatorSymbol: '×V',
    operandDimension: DIMENSIONS.VOLTAGE,
    outputQuantity: 'W',
    formula: 'W = q × V',
    educationalNote: 'Work done moving charge across electric potential difference: [T I] × [M L² T⁻³ I⁻¹] = [M L² T⁻²] (Joules).',
    calculateValue: (q) => Number((q * 20).toFixed(1)),
  },
  {
    id: 'q_times_E',
    name: 'Charge → Electric Force',
    domain: 'Electromagnetism',
    inputQuantity: 'q',
    operatorSymbol: '×E',
    operandDimension: DIMENSIONS.ELECTRIC_FIELD,
    outputQuantity: 'F',
    formula: 'F = q × E',
    educationalNote: 'Lorentz electrostatic force exerted on charge q in electric field E: [T I] × [M L T⁻³ I⁻¹] = [M L T⁻²] (Newtons).',
    calculateValue: (q) => Number((q * 15).toFixed(1)),
  },
  {
    id: 'W_div_q',
    name: 'Work → Voltage',
    domain: 'Electromagnetism',
    inputQuantity: 'W',
    operatorSymbol: '/q',
    operandDimension: DIMENSIONS.INVERSE_CHARGE,
    outputQuantity: 'V',
    formula: 'V = W / q',
    educationalNote: 'Electric potential is work done per unit electric charge: [M L² T⁻²] × [T⁻¹ I⁻¹] = [M L² T⁻³ I⁻¹].',
    calculateValue: (W) => Number((W / 4).toFixed(1)),
  },
  {
    id: 'F_div_q',
    name: 'Force → Electric Field',
    domain: 'Electromagnetism',
    inputQuantity: 'F',
    operatorSymbol: '/q',
    operandDimension: DIMENSIONS.INVERSE_CHARGE,
    outputQuantity: 'E_field',
    formula: 'E = F / q',
    educationalNote: 'Electric field is electric force per unit charge: [M L T⁻²] × [T⁻¹ I⁻¹] = [M L T⁻³ I⁻¹].',
    calculateValue: (F) => Number((F / 2).toFixed(1)),
  },
  {
    id: 'P_div_I',
    name: 'Power → Voltage',
    domain: 'Electromagnetism',
    inputQuantity: 'P',
    operatorSymbol: '/I',
    operandDimension: DIMENSIONS.INVERSE_CURRENT,
    outputQuantity: 'V',
    formula: 'V = P / I',
    educationalNote: 'Dividing electric power by current yields voltage: [M L² T⁻³] × [I⁻¹] = [M L² T⁻³ I⁻¹].',
    calculateValue: (P) => Number((P / 2).toFixed(1)),
  },
  {
    id: 'P_div_V',
    name: 'Power → Electric Current',
    domain: 'Electromagnetism',
    inputQuantity: 'P',
    operatorSymbol: '/V',
    operandDimension: DIMENSIONS.INVERSE_VOLTAGE,
    outputQuantity: 'I_elec',
    formula: 'I = P / V',
    educationalNote: 'Dividing electric power by potential difference yields current: [M L² T⁻³] × [M⁻¹ L⁻² T³ I] = [I].',
    calculateValue: (P) => Number((P / 12).toFixed(1)),
  },
  {
    id: 'q_times_v_times_B',
    name: 'Charge → Magnetic Lorentz Force',
    domain: 'Electromagnetism',
    inputQuantity: 'q',
    operatorSymbol: '×(vB)',
    operandDimension: new PhysicalDimensions(1, 1, -3, -1), // [L T⁻¹] × [M T⁻² I⁻¹] = [M L T⁻³ I⁻¹]
    outputQuantity: 'F',
    formula: 'F = q × v × B',
    educationalNote: 'Magnetic Lorentz force on moving charge: [T I] × [L T⁻¹] × [M T⁻² I⁻¹] = [M L T⁻²].',
    calculateValue: (q) => Number((q * 25).toFixed(1)),
  },
  {
    id: 'I_times_L_times_B',
    name: 'Current → Magnetic Wire Force',
    domain: 'Electromagnetism',
    inputQuantity: 'I_elec',
    operatorSymbol: '×(LB)',
    operandDimension: new PhysicalDimensions(1, 1, -2, -1), // [L] × [M T⁻² I⁻¹] = [M L T⁻² I⁻¹]
    outputQuantity: 'F',
    formula: 'F = I × L × B',
    educationalNote: 'Magnetic force on current-carrying wire of length L in magnetic field B: [I] × [L] × [M T⁻² I⁻¹] = [M L T⁻²].',
    calculateValue: (I) => Number((I * 20).toFixed(1)),
  },

  // ==========================================
  // 5. EVOLUTION BRIDGES & REVERSE RELATIONSHIPS
  // These keep every discovered branch connected instead of ending at energy.
  // ==========================================
  {
    id: 'KE_ddt',
    name: 'Kinetic Energy → Power',
    domain: 'Energy',
    inputQuantity: 'KE',
    operatorSymbol: 'd/dt',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'P',
    formula: 'P = d(KE)/dt',
    educationalNote: 'Power is the rate of energy transfer. When kinetic energy changes with time, its time derivative is the instantaneous power associated with that change.',
    calculateValue: (KE) => Number((KE * 0.45).toFixed(1)),
  },
  {
    id: 'PE_ddt',
    name: 'Potential Energy → Power',
    domain: 'Energy',
    inputQuantity: 'PE',
    operatorSymbol: 'd/dt',
    operandDimension: DIMENSIONS.INVERSE_TIME,
    outputQuantity: 'P',
    formula: 'P = d(PE)/dt',
    educationalNote: 'A changing potential energy corresponds to an energy transfer rate; the time derivative gives power.',
    calculateValue: (PE) => Number((PE * 0.35).toFixed(1)),
  },
  {
    id: 'omega_times_t',
    name: 'Angular Velocity → Angular Displacement',
    domain: 'Rotational',
    inputQuantity: 'omega',
    operatorSymbol: '×t',
    operandDimension: DIMENSIONS.TIME,
    outputQuantity: 'theta',
    formula: 'Δθ = ωt',
    educationalNote: 'For constant angular velocity, angular displacement is angular velocity multiplied by the elapsed time.',
    calculateValue: (omega) => Number((omega * 1.5).toFixed(2)),
  },
  {
    id: 'R_times_I',
    name: 'Resistance → Voltage',
    domain: 'Electromagnetism',
    inputQuantity: 'R',
    operatorSymbol: '×I',
    operandDimension: DIMENSIONS.CURRENT,
    outputQuantity: 'V',
    formula: 'V = IR',
    educationalNote: 'Ohm’s law relates resistance and current to potential difference.',
    calculateValue: (R) => Number((R * 3).toFixed(1)),
  },
  {
    id: 'W_div_V',
    name: 'Work → Charge',
    domain: 'Electromagnetism',
    inputQuantity: 'W',
    operatorSymbol: '/V',
    operandDimension: DIMENSIONS.INVERSE_VOLTAGE,
    outputQuantity: 'q',
    formula: 'q = W/V',
    educationalNote: 'Rearranging W = qV gives the charge transferred across a potential difference.',
    calculateValue: (W) => Math.max(1, Number((W / 20).toFixed(2))),
  },
  {
    id: 'F_div_E',
    name: 'Force → Charge',
    domain: 'Electromagnetism',
    inputQuantity: 'F',
    operatorSymbol: '/E',
    operandDimension: DIMENSIONS.INVERSE_CHARGE,
    outputQuantity: 'q',
    formula: 'q = F/E',
    educationalNote: 'Rearranging F = qE gives the charge experiencing a known electric field.',
    calculateValue: (F) => Math.max(1, Number((F / 15).toFixed(2))),
  },
  {
    id: 'E_times_q',
    name: 'Electric Field → Electric Force',
    domain: 'Electromagnetism',
    inputQuantity: 'E_field',
    operatorSymbol: '×q',
    operandDimension: DIMENSIONS.CHARGE,
    outputQuantity: 'F',
    formula: 'F = qE',
    educationalNote: 'An electric field exerts force on charge: F = qE.',
    calculateValue: (E) => Number((E * 1.8).toFixed(1)),
  },
  {
    id: 'B_times_qv',
    name: 'Magnetic Field → Lorentz Force',
    domain: 'Electromagnetism',
    inputQuantity: 'B_field',
    operatorSymbol: '×(qv)',
    operandDimension: new PhysicalDimensions(-1, 0, 3, 1),
    outputQuantity: 'F',
    formula: 'F = qvB',
    educationalNote: 'The magnetic part of the Lorentz force has magnitude F = qvB for perpendicular velocity and magnetic field.',
    calculateValue: (B) => Number((B * 2).toFixed(1)),
  },
  {
    id: 'F_div_qv',
    name: 'Force → Magnetic Field',
    domain: 'Electromagnetism',
    inputQuantity: 'F',
    operatorSymbol: '/(qv)',
    operandDimension: new PhysicalDimensions(-1, 0, 3, 1),
    outputQuantity: 'B_field',
    formula: 'B = F/(qv)',
    educationalNote: 'For perpendicular motion, rearranging F = qvB isolates the magnetic field.',
    calculateValue: (F) => Math.max(0.1, Number((F / 25).toFixed(2))),
  },

  {
    id: 'alpha_integral_dt',
    name: 'Angular Acceleration → Angular Velocity',
    domain: 'Rotational',
    inputQuantity: 'alpha',
    operatorSymbol: '∫dt',
    operandDimension: DIMENSIONS.TIME,
    outputQuantity: 'omega',
    formula: 'ω = ∫α dt',
    educationalNote: 'Integrating angular acceleration over time gives the change in angular velocity; the game uses a simplified state transformation.',
    calculateValue: (alpha) => Number((alpha * 0.9).toFixed(2)),
  },
];
